Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: uk.nhs.england.fwoa.Handler
      CodeUri: C:\Development\NHSDigital\fhir-validation-lambda
      Runtime: java11
      Architectures:
        - x86_64