server:
  port: 9001
  tomcat:
    threads:
      max: 10

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: IOPS FHIR Testing
    baseUrl: https://3cdzg7kbj4.execute-api.eu-west-2.amazonaws.com/poc/Conformance
    version: 2.6.29


