server:
  port: 9001
  tomcat:
    threads:
      max: 10
  forward-headers-strategy: native

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: NHS England Interoperability Standards FHIR Testing
    baseUrl: http://localhost:9001
    version: 6.10.27

services:
  R4: true
  STU3: true
  LOINC: false
  R4B: false

###Remote terminology validation:

##Example without auth:
#terminology:
#  url: https://r4.ontoserver.csiro.au/fhir

##Example with auth:
#terminology:
#  url: https://ontology.nhs.uk/authoring/fhir/
#  authorization:
#    tokenUrl: https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token
#    clientId: test
#    clientSecret: test
